# Generated by Django 3.0.6 on 2020-06-30 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.UUIDField(unique=True, verbose_name='device_id')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='api.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='id')),
                ('state', models.IntegerField(verbose_name='state')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.Customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.Device')),
            ],
        ),
    ]
