# Generated by Django 3.0.6 on 2020-07-01 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executed',
            field=models.BooleanField(default=False, verbose_name='execute'),
        ),
        migrations.AddField(
            model_name='task',
            name='result',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='result'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(verbose_name='device_id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(default=0, verbose_name='state'),
        ),
    ]
