# Generated by Django 3.0.6 on 2020-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200701_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(unique=True, verbose_name='device_id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(unique=True, verbose_name='id'),
        ),
    ]
